### ISSUE TITLE
Recommend that `BinTest` should not be ran on multiple threads

### ISSUE THREAD

**Issue by samuelsleight** [cehteh/bintest#7]
When setting up integration tests in my project, I was seeing [infrequent, non-deterministic test failures](https://github.com/samuelsleight/catastrophic-lang/actions/runs/7533220018/job/20506401160) which I eventually narrowed down to being a result of the test binary running each test in parallel, which therefore runs `BinTest` in parallel, which it appears has a _chance_ of interfering with the running of the compiled excutable in another test.

Based on the discussion [here](https://github.com/cehteh/bintest/pull/6#issuecomment-1944039323), I think it's worth, as you say, either explicitly documenting the recommendation that `BinTest` should only be ran once (using `lazy_static` or `Lazy` or similar) or handling it internal to `BinTest` as part of the API

**Comment by cehteh** [comment]
On Wed, 14 Feb 2024 12:23:09 -0800
Samuel Sleight ***@***.***> wrote:

> When setting up integration tests in my project, I was seeing
> [infrequent, non-deterministic test
> failures](https://github.com/samuelsleight/catastrophic-lang/actions/runs/7533220018/job/20506401160)
> which I eventually narrowed down to being a result of the test binary
> running each test in parallel, which therefore runs `BinTest` in
> parallel, which it appears has a _chance_ of interfering with the
> running of the compiled excutable in another test.
> 
> Based on the discussion
> [here](https://github.com/cehteh/bintest/pull/6#issuecomment-1944039323),
> I think it's worth, as you say, either explicitly documenting the
> recommendation that `BinTest` should only be ran once (using
> `lazy_static` or `Lazy` or similar) or handling it internal to
> `BinTest` as part of the API 
> 

I am right now working on making it a singleton, thats a API change but
should be worthwhile

**Comment by samuelsleight** [comment]
Yeah, that sounds like a sensible API change to me

**Comment by cehteh** [comment]
On Wed, 14 Feb 2024 12:29:51 -0800
Samuel Sleight ***@***.***> wrote:

> Yeah, that sounds like a sensible API change to me
> 

Actually it is not *that* trivial on a second thought, since we can
have multiple builders/instances that are differently configured. This
has the bug you noticed currently as it runs 'cargo build' in parallel.
Strange that this has such side effects, I thought that would be
sane/atomic.

What we need is one singleton per configuration AND tests runninng on
different configurations should be mutually exclusive. Am I right with
this thinking?

Then thinking further lets say you have some different configs multiple
tests for each config, just mutually exclusive isnt enough, we need to
build each config once, run all its tests (in parallel), then build the
next config, run thoses tests and so on.

So we need to collect all configs/test combinations in a btree or
something like that, ensure that only on config is build and its tests
are run before progressing with the next set...

Looks like this is some more fun.

**Comment by samuelsleight** [comment]
> Strange that this has such side effects, I thought that would be
sane/atomic.

That _is_ a good point, I wonder if there's a `cargo` bug there - I did think that `cargo` was supposed to be locking sensibly on builds?

> What we need is one singleton per configuration AND tests runninng on
different configurations should be mutually exclusive. Am I right with
this thinking?
>
>Then thinking further lets say you have some different configs multiple
tests for each config, just mutually exclusive isnt enough, we need to
build each config once, run all its tests (in parallel), then build the
next config, run thoses tests and so on.

Yeah, that sounds correct to me - definitely feels less simple than it initially seemed! At the very least, "configuration" probably doesn't need to be "every combination of builder parameters", as it's only `debug` versus `release` I think at the moment that will affect the outcome?

**Comment by cehteh** [comment]
On Wed, 14 Feb 2024 12:55:28 -0800
Samuel Sleight ***@***.***> wrote:

> > Strange that this has such side effects, I thought that would be  
> sane/atomic.
> 
> That _is_ a good point, I wonder if there's a `cargo` bug there - I
> did think that `cargo` was supposed to be locking sensibly on builds?
> 
> > What we need is one singleton per configuration AND tests runninng
> > on  
> different configurations should be mutually exclusive. Am I right with
> this thinking?
> >
> >Then thinking further lets say you have some different configs
> >multiple  
> tests for each config, just mutually exclusive isnt enough, we need to
> build each config once, run all its tests (in parallel), then build
> the next config, run thoses tests and so on.
> 
> Yeah, that sounds correct to me - definitely feels less simple than
> it initially seemed! At the very least, "configuration" probably
> doesn't need to be "every combination of builder parameters", as it's
> only `debug` versus `release` I think at the moment that will affect
> the outcome?

the build_workspace() build_executable() will affect the artifacts
build as well, in future even more flags might be added so for
future-proofness and correctness I would just put the whole config into
a hash or find some other (manual) way to schedule tests.

Or maybe disallowing different configs at all, that would be the low
hanging fruit. A BinTest singleton can then be initialized only once
any further attempt will panic.

**Comment by samuelsleight** [comment]
Ah, yeah, that's true.

Feels like scheduling tests could be a very big can of worms to open up, perhaps that bit _is_ better left just documented? It's low hanging fruit, but the "better" solution might be _very_ high up the tree

**Comment by cehteh** [comment]
@samuelsleight I added a Singleton/check now. With some nice Idea keeping the API compatible. Could you please give this some battle testing?

**Comment by samuelsleight** [comment]
That all looks nice and sensible, I'll give it a test now!

**Comment by cehteh** [comment]
On Fri, 16 Feb 2024 09:53:47 -0800
Samuel Sleight ***@***.***> wrote:

> That all looks nice and sensible, I'll give it a test now!
> 

This is just some incremental change trying to keep the API compatible.
I may change the API next so that .new() and .with().build()  return
the Singleton as &'static Self directly instead cloning. This would be
a breaking change but shouldnt be really noticeable.

**Comment by samuelsleight** [comment]
Well, I've ran a bunch of repeats of my CI with upgraded `bintest` and it seems to be working nicely! I'll leave [my PR](https://github.com/samuelsleight/catastrophic-lang/pull/31) open for now whilst you contemplate other API changes, so I can do a complete upgrade in one go, but in terms of the singleton all seems good

**Comment by cehteh** [comment]
On Fri, 16 Feb 2024 10:38:21 -0800
Samuel Sleight ***@***.***> wrote:

> Well, I've ran a bunch of repeats of my CI with upgraded `bintest`
> and it seems to be working nicely! I'll leave [my
> PR](https://github.com/samuelsleight/catastrophic-lang/pull/31) open
> for now whilst you contemplate other API changes, so I can do a
> complete upgrade in one go, but in terms of the singleton all seems
> good
> 

2 more commits I think I am happy now, please test. This has the
(typically not noticeable) breaking API change returning a reference to
the singleton instead instance. Also lifts the 'RELEASE_BUILD' flag
into the builder.

When you are fine with this i think this can be a 2.0 release

**Comment by samuelsleight** [comment]
Yep, that was a drop in replacement for me, and everything still works nicely!

**Comment by cehteh** [comment]
On Fri, 16 Feb 2024 11:17:22 -0800
Samuel Sleight ***@***.***> wrote:

> Yep, that was a drop in replacement for me, and everything still
> works nicely!
> 

Ok, practically ready for release i'd say, feel free to send me some
PR/Doc improvements I am not 100% satisfied with that yet, but its not
a blocker. I give it some time too cool off and then can make a release
at any time, nag me when you need it.

**Comment by samuelsleight** [comment]
Cool, I'll give all the docs a proper read through this weekend then, but in terms of functionality I'm pretty sure I'm happy

**Comment by cehteh** [comment]
On Fri, 16 Feb 2024 11:21:27 -0800
Samuel Sleight ***@***.***> wrote:

> Cool, I'll give all the docs a proper read through this weekend then,
> but in terms of functionality I'm pretty sure I'm happy

So .. I did some cleanup and some breaking changes in anticipation for
a v2.0, please check. I think this is much nicer and more complete now.

notably breaking changes are:

* rename the configuration methods to be more in line with the cli
    args:
     * .build_workspace() -> .workspace()
     * .build_executable() -> .binaries() // should be bin() but thats
    too confusing takes a static `&[&str]` now

* re-added .binary() and .example()

* remove bool arguments from the builder methods
  eg.: .quiet(true) is just .quiet() now

**Comment by samuelsleight** [comment]
Sorry, been busy for a couple of weeks but have updated my code to these changes now!

I agree, this feels nicer now, I'm pretty happy with this

**Comment by cehteh** [comment]
🎉 v2.0.0 released with all the new features.
